CREATE TABLE user_authorities
(
    user_id     BIGINT       NOT NULL,
    authorities VARCHAR(255) NOT NULL
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    hashed_pass VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE user_authorities
    ADD CONSTRAINT fk_user_authorities_on_user FOREIGN KEY (user_id) REFERENCES users (id);